from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.text import slugify

# Create your models here.
class Page(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField(blank=True)
    author = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        help_text="The user that posted this article.")
    created_on = models.DateTimeField(
        auto_now_add=True,
        help_text="The date and time this page was created. Automatically generated when the model saves.")
    modified_on = models.DateTimeField(auto_now=True,
        help_text="The date and time this page was updated. Automatically generated when the model updates.")
    slug = models.CharField(
        max_length=255,
        editable=False,
        help_text="Unique URL path to access this page. Generated by the system.")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """ Returns path via slug """
        return reverse('page-detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        """ Creates a URL safe slug automatically when a new page is created. """
        if not self.pk:
            self.slug = slugify(self.title, allow_unicode=True)

        # Call save on the superclass.
        return super(Page, self).save(*args, **kwargs)
