# Generated by Django 3.1.7 on 2021-03-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(help_text='Birthday'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='firstName',
            field=models.CharField(blank=True, help_text='First name', max_length=255, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastName',
            field=models.CharField(blank=True, help_text='Last name', max_length=255, verbose_name='Last Name'),
        ),
    ]
